kingdom_homes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import Static_Sitemap
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact-us/', views.contact, name='contact_us'),
    path('booking/', views.booking, name='booking'),
    path('book-with-us/', views.booking_page, name='booking_page'),
    path('inner-page/', views.inner_page, name='inner_page'),
    path('sitemap.xml', sitemap, {'sitemaps': {"static": Static_Sitemap}},
         name='django.contrib.sitemaps.views.sitemap')
    # path('privacy-policy/', views.privacy, name='privacy'),
    # path('disclaimer/', views.disclaimer, name='disclaimer'),
]

website/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=500)
    phone_number = PhoneNumberField()

    def __str__(self):
        return self.email


# Create your models here.
class Booking(models.Model):
    book_name = models.CharField(max_length=100)
    book_email = models.EmailField(max_length=150)
    book_phone = PhoneNumberField()
    book_date = models.DateField()
    book_time = models.TimeField()
    book_n_people = models.IntegerField()
    book_subject = models.TextField(max_length=100)
    book_message = models.CharField(max_length=500)

    def __str__(self):
        return self.email


class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="testimonials/", blank=True, null=True)
    testimonial = models.TextField(max_length=500)
    stars = models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    order = models.IntegerField(null=True)

    def __str__(self):
        return f"testimonial from: {self.name}"


class Team(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    short_desc = models.TextField(max_length=500)
    photo = models.ImageField(upload_to="team_pictures/", null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)

    # social media
    twitter = models.CharField(max_length=200, default="#")
    facebook = models.CharField(max_length=200, default="#")
    instagram = models.CharField(max_length=200, default="#")
    linkedin = models.CharField(max_length=200, default="#")

    def __str__(self):
        return self.name

website/forms.py
from django import forms
from .models import Contact, Booking
from phonenumbers import is_valid_number, is_possible_number
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.core.exceptions import ValidationError

# Create your forms here.

CONTACT_PLACE_HOLDERS = {
    "Name": "What is your name?",
    "Email": "What is your email address?",
    "Subject": "Subject",
    "Message": "Message",
}

BOOKING_PLACE_HOLDERS = {
    "Book Name": "Your name",
    "Book Email": "Your Email",
    "Book Phone": "Your Phone",
    "Book Date": "Date of Check-In (YYYY-MM-DD)",
    "Book Time": "Time of Check-In (HH:MM:SS)",
    "Book N People": "# of People",
    "Book Subject": "Subject",
    "Book Message": "Message"
}


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({
            'rows': 5
        })
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = CONTACT_PLACE_HOLDERS.get(field.label.title())


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = '__all__'

        widgets = {
            'Book Date': forms.DateInput(format='%Y-%m-%d', attrs={"type": "datetime-local"}),
            'Book Time': forms.DateInput(format='%H:%M:%S', attrs={"type": "datetime-local"}),
            "Phone Number": PhoneNumberPrefixWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = BOOKING_PLACE_HOLDERS.get(field.label.title())

website/views.py
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm, BookingForm
from kingdom_homes.settings import EMAIL_HOST_USER

# Create your views here.


def index(request):
    contact_form = ContactForm()
    context = {
        "contact_form": contact_form,
    }
    return render(request, 'website/index.html', context)


def inner_page(request):
    context = {}
    return render(request, 'website/sample-inner-page.html', context)


def booking_page(request):
    booking_form = BookingForm()
    context = {
        "booking_form": booking_form
    }
    return render(request, 'website/booking.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            print(form.cleaned_data)
            body = {
                'name': form.cleaned_data['name'],
                'subject': form.cleaned_data['subject'],
                'email': form.cleaned_data['email'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            form.save()

            try:
                send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            # return HttpResponse("Your query has been sent.", status=200)
            return HttpResponse("Message sent successfully", status=200)

    form = ContactForm()
    return render(request, 'website/index.html', {'form': form})


def booking(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            subject = "Kingdom Homes Booking Request"
            print(form.cleaned_data)
            body = {
                    'Name': form.cleaned_data['book_name'],
                    'Email': form.cleaned_data['book_email'],
                    "Phone": form.cleaned_data['book_phone'],
                    "Date": form.cleaned_data['book_date'],
                    "Time": form.cleaned_data['book_time'],
                    "People": form.cleaned_data['book_n_people'],
                    "Subject": form.cleaned_data['book_subject']
                }
            email_header = "A new client is trying to contact you:"
            message = "\n".join([email_header] + [f"{key}: {str(value)}" for key, value in body.items()])
            response = "Your message has been sent. Thank you!"
            try:
                send_mail(subject, message, body.get('email'), [EMAIL_HOST_USER])
            except BadHeaderError:
                response = "Bad Header Sent"
                return HttpResponse(response)
            return HttpResponse(response, status=200)
        else:
            response = {}
            return JsonResponse(response, status=403)
    else:
        form = ContactForm()
    return render(request, 'website/index.html', {'form': form})

# def about(request):
#     context = {}
#     return render(request, 'website/about.html', context)
#
#
# def privacy(request):
#     context = {}
#     return render(request, 'website/privacy-policy.html', context)
#
#
# def disclaimer(request):
#     context = {}
#     return render(request, 'website/disclaimer.html', context)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} Home {% endblock title %} - Kingdom Home Stays</title>
    {% load static %}
    {% block head_meta %}
    <meta content="" name="description">
    <meta content="" name="keywords">
    {% endblock head_meta %}


    {% block head_favicon %}
    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    {% endblock head_favicon %}

    {% block fonts %}
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    {% endblock fonts %}

    {% block vendor_css %}
    <!-- Vendor CSS Files -->
    <link href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    {% endblock vendor_css %}

    {% block main_css %}
    <!-- Template Main CSS File -->
    <link href="assets/css/main.css" rel="stylesheet">
    {% endblock main_css %}
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

        <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-lg-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1>Kingdom Home Stays<span>.</span></h1>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="{% url 'index' %}#hero">Home</a></li>
                <li><a href="{% url 'index' %}#about">About</a></li>
                <li><a href="{% url 'index' %}#menu">Menu</a></li>
                <li><a href="{% url 'index' %}#events">Events</a></li>
                <li><a href="{% url 'index' %}#chefs">Chefs</a></li>
                <li><a href="{% url 'index' %}#gallery">Gallery</a></li>
                <li class="dropdown"><a href="#"><span>Drop Down</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                            <ul>
                                <li><a href="#">Deep Drop Down 1</a></li>
                                <li><a href="#">Deep Drop Down 2</a></li>
                                <li><a href="#">Deep Drop Down 3</a></li>
                                <li><a href="#">Deep Drop Down 4</a></li>
                                <li><a href="#">Deep Drop Down 5</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'index' %}#contact">Contact</a></li>
            </ul>
        </nav><!-- .navbar -->

        <a class="btn-book-a-table" href="{% url 'index' %}#book-a-table">Book a Table</a>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header><!-- End Header -->

<div id="site-wrapper">
    {% block content %}
    if you see this, something is wrong!
    {% endblock content %}
</div>

<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

    <div class="container">
        <div class="row gy-3">
            <div class="col-lg-3 col-md-6 d-flex">
                <i class="bi bi-geo-alt icon"></i>
                <div>
                    <h4>Address</h4>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022 - US<br>
                    </p>
                </div>

            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="bi bi-telephone icon"></i>
                <div>
                    <h4>Reservations</h4>
                    <p>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="bi bi-clock icon"></i>
                <div>
                    <h4>Opening Hours</h4>
                    <p>
                        <strong>Mon-Sat: 11AM</strong> - 23PM<br>
                        Sunday: Closed
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
                <h4>Follow Us</h4>
                <div class="social-links d-flex">
                    <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Kingdom Home Stays</span></strong>. All Rights Reserved
        </div>
    </div>

</footer><!-- End Footer -->
<!-- End Footer -->

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<div id="preloader"></div>

{% block footer_js %}

<!-- Vendor JS Files -->
{% block footer_vendor_js %}
<script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/vendor/aos/aos.js' %}"></script>
<script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--<script src="assets/vendor/php-email-form/validate.js"></script>-->

<!-- Template Main JS File -->
{% block footer_site_js %}
<script src="{% static 'website/js/main.js' %}"></script>
{% endblock footer_site_js %}

{% block page_js %}
<!--Any page specific javascript-->
{% endblock page_js %}

{% endblock footer_js %}

</body>

</html>

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} Home {% endblock title %} - Kingdom Homes Stays</title>
    {% load static %}
    {% block head_meta %}
    <meta content="Do you have a property you need to rent? We are a local hospitality company in the United States and we're looking for rentals just like yours! We are Kingdom Home Stays"
          name="description">
    <meta content="" name="keywords">
    {% endblock head_meta %}


    {% block head_favicon %}
    <!-- Favicons -->
    <link href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link href="{% static 'website/img/favicon.png' %}" rel="apple-touch-icon">
    {% endblock head_favicon %}

    {% block fonts %}
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    {% endblock fonts %}

    {% block javascript %}
    <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
    {% endblock javascript %}

    {% block vendor_css %}
    <!-- Vendor CSS Files -->
    <link href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    {% endblock vendor_css %}

    {% block main_css %}
    <!-- Template Main CSS File -->
    <link href="{% static 'website/css/main.css' %}" rel="stylesheet">
    {% endblock main_css %}

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-RWBTLNZJ4G"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-RWBTLNZJ4G');

    </script>
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

        <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-lg-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <img src="{% static 'website/img/logo/logo.png' %}" alt="">
            <!--            <h1>Kingdom Home Stays<span>.</span></h1>-->
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="{% url 'index' %}#hero">Home</a></li>
                <li><a href="{% url 'index' %}#about">About</a></li>
                <li><a href="{% url 'index' %}#events">Stays</a></li>
                <!--                <li><a href="{% url 'index' %}#gallery">Gallery</a></li>-->
                <li><a href="{% url 'index' %}#contact">Contact</a></li>
            </ul>
        </nav><!-- .navbar -->

        <a class="btn-book-a-stay" href="{% url 'index' %}#contact">Contact Us</a>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header><!-- End Header -->

<div id="site-wrapper">
    {% block content %}
    if you see this, something is wrong!
    {% endblock content %}
</div>

<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

    <div class="container">
        <div class="row gy-3">
            <div class="col-lg-4 col-md-6 d-flex">
                <i class="bi bi-geo-alt icon"></i>
                <div>
                    <h4>Address</h4>
                    <p>
                        3514 Sebring <br>Ave Orlando,<br>FL 32806
                    </p>
                </div>

            </div>

            <div class="col-lg-4 col-md-6 footer-links d-flex">
                <i class="bi bi-telephone icon"></i>
                <div>
                    <h4>Contact Us</h4>
                    <p>
                        <strong>Phone:</strong> +1 (407) 217-3056<br>
                        <strong>Email:</strong> kingdomhomesstays@gmail.com<br>
                    </p>
                </div>
            </div>


            <div class="col-lg-4 col-md-6 footer-links">
                <h4>Follow Us</h4>
                <div class="social-links d-flex">
                    <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Kingdom Homes Stays</span></strong>. All Rights Reserved
        </div>
    </div>

    <div class="credits"> Designed and developed by <a href="https://aiprizm.herokuapp.com/">AiPrizm Technologies</a>
    </div>

</footer><!-- End Footer -->
<!-- End Footer -->

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<div id="preloader"></div>

{% block footer_js %}

<!-- Vendor JS Files -->
{% block footer_vendor_js %}
<script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/vendor/aos/aos.js' %}"></script>
<script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--<script src="assets/vendor/php-email-form/validate.js"></script>-->
{% endblock footer_vendor_js %}


<!-- Template Main JS File -->
{% block footer_site_js %}
<script src="{% static 'website/js/main.js' %}"></script>
{% endblock footer_site_js %}

{% block page_js %}
<!--Any page specific javascript-->
{% endblock page_js %}

{% endblock footer_js %}

</body>

</html>

website/templates/website/booking.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Booking{% endblock title %}

{% block content %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Book with Us</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Bookings</li>
          </ol>
        </div>

      </div>
    </div><!-- End Breadcrumbs -->

        <!-- ======= Book a Property Section ======= -->
    <section id="book-a-stay" class="book-a-stay">
        <div class="container" data-aos="fade-up">

            <div class="section-header">
                <h2>Book a Property</h2>
                <p>Book <span>Your Stay</span> With Us</p>
            </div>

            <div class="row g-0">

                <div class="col-lg-4 reservation-img"
                     style='background-image: url("/static/website/img/reservation.jpg");' data-aos="zoom-out"
                     data-aos-delay="200"></div>

                <div class="col-lg-8 d-flex align-items-center reservation-form-bg">
                    <form action="" method="post" role="form" class="php-email-form" data-aos="fade-up"
                          data-aos-delay="100">
                        <div class="row gy-4">
                            {{ booking_form.non_field_errors }}
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_name.errors }}
                                {{ booking_form.book_name }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_email.errors }}
                                {{ booking_form.book_email }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_phone.errors }}
                                {{ booking_form.book_phone }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_date.errors }}
                                {{ booking_form.book_date }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_time.errors }}
                                {{ booking_form.book_time }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                {{ booking_form.book_n_people.errors }}
                                {{ booking_form.book_n_people }}
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            {{ booking_form.book_subject.errors }}
                            {{ booking_form.book_subject }}
                            <div class="validate"></div>
                        </div>
                        <div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="error-message">Something went wrong, contact us as
                                kingdom_homesstays@gmail.com
                            </div>
                            <div class="sent-message">Your booking request was sent. We will call back or send
                                an e-mail
                                to confirm your reservation. Thank you!
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit">Book a Property</button>
                        </div>
                    </form>
                </div><!-- End Reservation Form -->

            </div>

        </div>
    </section><!-- End Book a Property Section -->


  </main><!-- End #main -->
{% block page_js %}
<script type='text/javascript'>

  $(document).ready(function(){

    // AJAX for posting
    function book_with_us() {
        $(".sent-message, .error-message").removeClass("d-block");
        $.ajax({
            headers: {'X-Requested-With': 'XMLHttpRequest'},
            url : "{% url 'contact_us' %}", // the endpoint
            type : "POST", // http method
            data : {
              book_name: $('#id_book_name').val(),
              book_email: $('#id_book_email').val(),
              book_phone: $('#id_book_phone').val(),
              book_date: $('#id_book_date').val(),
              book_time: $('#id_book_time').val(),
              book_n_people: $('#id_book_n_people').val(),
              book_subject: $('#id_book_subject').val(),
              csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            }, // data sent with the post request
            // handle a successful response
            success : function(response) {
                // remove the value from the input
                $('#id_name').val('');
                $('#id_book_email').val(); // remove the value from the input
                $('#id_book_phone').val(); // remove the value from the input
                $('#id_book_date').val();
                $('#id_book_time').val();
                $('#id_book_n_people').val();
                $('#id_book_subject').val();
                $(".sent-message").html(response.responseText);
                $(".sent-message").addClass("d-block");
            },

            // handle a non-successful response
            error : function(response) {
                var err_msg = $.parseJSON(response.responseText);
                var error = "";
                $.each(err_msg, function(key, value){
                    console.log( "Key: " + key + ", Value: " + value );
                    error += "<p>" + value + "</p>"
                })
                $(".error-message").html(error);
                $(".error-message").addClass("d-block");
            }
        });
    }

    // Submit post on submit
    $('.php-email-form').off().on('submit', function(event){
        event.preventDefault();
        event.stopPropagation();
        book_with_us();
    });

})
</script>

{% endblock page_js %}

{% endblock content %}

website/templates/website/sample-inner-page.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Sample Inner Page</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Sample Inner Page</li>
          </ol>
        </div>

      </div>
    </div><!-- End Breadcrumbs -->

    <section class="sample-page">
      <div class="container" data-aos="fade-up">

        <p>
          You can duplicate this sample page and create any number of inner pages you like!
        </p>

      </div>
    </section>

  </main><!-- End #main -->

{% endblock content %}